# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_q.Task')),
            ],
        ),
    ]
