# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0010_tasklogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklogger',
            name='task',
        ),
        migrations.AddField(
            model_name='tasklogger',
            name='task_id',
            field=models.CharField(default='aaabbbccc', max_length=32),
            preserve_default=False,
        ),
    ]
